In [40]:
import pandas as pd
import numpy as np

data = {
    'customer_name': ['Shash', 'Bala', 'Deepa', 'Esha', 'Bala', 'park','bala','bala'],
    'city': ['Bangalore', 'Delhi', 'Delhi','Bangalore', 'Delhi','bangalore','delhi','delhi'],
    'order_value': [5000, 7000, np.nan, 6500, 7000, 6500,7000,7000],
    'Email': ['shash@gmail.com', 'bala@reddif.com', 'bala@gmail.com',
             'esha@gmail.com', 'bala@yahoo.com', 'park@gmail.com','bala@gmail.com','bala@gmail.com']   
}
df = pd.DataFrame(data)
df

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0  bala@reddif.com
2         Deepa      Delhi          NaN   bala@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
4          Bala      Delhi       7000.0   bala@yahoo.com
5          park  bangalore       6500.0   park@gmail.com
6          bala      delhi       7000.0   bala@gmail.com
7          bala      delhi       7000.0   bala@gmail.com

#Handling duplicate values
duplicates occurs when the same record appears multiple times in a dataset

common reasons :-
data entry errors
merging datasets
system logging errors
duplicates can distort the analysis, for ex
revenue may appear higher than reality

In [10]:
#viewing duplicate rows
df[df.duplicated()]

  customer_name   city  order_value           Email
4          Bala  Delhi       7000.0  bala@gmail.com

In [ ]:
#identify the duplicate values
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [16]:
#removes completely identical rows
df.drop_duplicates()

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
2         Deepa      Delhi          NaN  deepa@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [17]:
df1=df.drop_duplicates()
print(df1)
print(df)

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
2         Deepa      Delhi          NaN  deepa@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com
  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
2         Deepa      Delhi          NaN  deepa@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
4          Bala      Delhi       7000.0   bala@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [20]:
df.drop_duplicates(inplace=True)
df

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
2         Deepa      Delhi          NaN  deepa@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [25]:
#using subset
df1=df.drop_duplicates(subset='Email')
df1
#this removes duplictes only based on the email column

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [27]:
df1=df.drop_duplicates(subset='city')
df1

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [34]:
#keep decides which duplicates record remains
df1=df.drop_duplicates(keep='first')
df1

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
1          Bala      Delhi       7000.0   bala@gmail.com
2         Deepa      Delhi          NaN   bala@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com
6          bala      delhi       7000.0   bala@gmail.com

In [35]:
#keep decides which duplicates record remains
df1=df.drop_duplicates(keep='last')
df1

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
2         Deepa      Delhi          NaN   bala@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
4          Bala      Delhi       7000.0   bala@gmail.com
5          park  bangalore       6500.0   park@gmail.com
7          bala      delhi       7000.0   bala@gmail.com

In [ ]:
#keep decides which duplicates record remains
df1=df.drop_duplicates(keep=False)
df1
#keep parameters accepts only three values-first-last-False

  customer_name       city  order_value            Email
0         Shash  Bangalore       5000.0  shash@gmail.com
2         Deepa      Delhi          NaN   bala@gmail.com
3          Esha  Bangalore       6500.0   esha@gmail.com
5          park  bangalore       6500.0   park@gmail.com

In [37]:
#string operation with .str
#text columns in pandas can use the .str accessor which allows vectorised string operations

df['city'].str.lower()

0    bangalore
1        delhi
2        delhi
3    bangalore
4        delhi
5    bangalore
6        delhi
7        delhi
Name: city, dtype: str

In [38]:
df['city'].str.upper()

0    BANGALORE
1        DELHI
2        DELHI
3    BANGALORE
4        DELHI
5    BANGALORE
6        DELHI
7        DELHI
Name: city, dtype: str

In [41]:
df['Email'].str.contains('gmail')

0     True
1    False
2     True
3     True
4    False
5     True
6     True
7     True
Name: Email, dtype: bool

In [42]:
df['customer_name'].str.strip()
#removes extra spaces
#useful when data comes from forms or excel sheets

0    Shash
1     Bala
2    Deepa
3     Esha
4     Bala
5     park
6     bala
7     bala
Name: customer_name, dtype: str

In [43]:
df['Email'].str.replace('gmail.com','gmail.co')

0     shash@gmail.co
1    bala@reddif.com
2      bala@gmail.co
3      esha@gmail.co
4     bala@yahoo.com
5      park@gmail.co
6      bala@gmail.co
7      bala@gmail.co
Name: Email, dtype: str

In [46]:
df[df['Email'].str.startswith('e')]

  customer_name       city  order_value           Email
3          Esha  Bangalore       6500.0  esha@gmail.com

In [47]:
df['Email'].str.split('@')

0    [shash, gmail.com]
1    [bala, reddif.com]
2     [bala, gmail.com]
3     [esha, gmail.com]
4     [bala, yahoo.com]
5     [park, gmail.com]
6     [bala, gmail.com]
7     [bala, gmail.com]
Name: Email, dtype: object

In [48]:
df['Greeting']="hello"+" "+df['customer_name']
print(df['Greeting'])

0    hello Shash
1     hello Bala
2    hello Deepa
3     hello Esha
4     hello Bala
5     hello park
6     hello bala
7     hello bala
Name: Greeting, dtype: str

In [ ]:
#REGEX - regular expressions
#to extract patterns from text

common regex patterns

\d               digit
\w               letter or number
^                start of a string
$                end of string 
.                any character
+                one or more
-                zero or more


commonly used with - 
.str.contains()
.str.extract()
.str.replace()
.str.match()

In [20]:
import pandas as pd
data={"Email":["asha123@gmail.com",
               "bala@yahoo.com",
               "shash@gmail.com",
               "chitra_98@company.com"]}
df=pd.DataFrame(data)

In [2]:
#extract numbers from text
df["Email"].str.extract(r"(\d+)")

     0
0  123
1  NaN
2   98

In [3]:
#find rows containing numbers
df["Email"].str.contains(r"\d")

0     True
1    False
2     True
Name: Email, dtype: bool

In [7]:
#extract email domain
df["Email"].str.extract(r"@(\w+)")

       0
0  gmail
1  yahoo
2  gmail

when we write @(\w+)
()                   capture group
\w                   letter or number
+                    one or more

here match starts at the symbol @ but since @ is outside of the capture group it is not extracted so only what is inside capture group() is extracted

In [8]:
#find emails ending with gmail.com
df["Email"].str.contains(r"@gmail\.com$")

0     True
1    False
2    False
Name: Email, dtype: bool

In [12]:
data={"name":["asha","bala","chitra","deepa"]}
df=pd.DataFrame(data)

In [13]:
#find names starting with A
df["name"].str.contains(r"^a")

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [18]:
#remove numbers from emails
df["Email"].str.replace(r"\d"," ")

0       asha123@gmail.com
1          bala@yahoo.com
2         shash@gmail.com
3    chitra98@company.com
Name: Email, dtype: str

In [21]:
#regex groups
#chitra98@gmail.com
#we want to extract both name and number in the email seperately
df["Email"].str.extract(r"(\w+)_(\d+)")

        0    1
0     NaN  NaN
1     NaN  NaN
2     NaN  NaN
3  chitra   98