concatenation- pd.concat()

concatenation means combinig dataframes by stacking them

two main ways to stack:-

vertical stacking      axis=0
horizontal stacking    axis=1

In [1]:
import pandas as pd
df1=pd.DataFrame({
    "Customer":["Asha","Bala"],
    "City":["Bangalore","Mumbai"]
})
df1

  Customer       City
0     Asha  Bangalore
1     Bala     Mumbai

In [ ]:
#stack rows
#vertical stackings or adding more rows

pd.concat([df1,df2],axis=0)

In [ ]:
pd.concat([df1,df2],axis=0).reset_index(drop=True)

In [ ]:
df3=pd.DataFrame({"Sales":[50000,30000]})

df4=pd.DataFrame({"Quantity":[2,1]})

In [ ]:
#horizontal stacking or adding more columns
pd.concat([df3,df4],axis=1)

   Sales  Quantity
0  50000         2
1  30000         1

In [2]:
#vertical concatenation

import pandas as pd
jan=pd.DataFrame({
    "Customer":["Asha","Sanjana"],
    "City":["Bangalore","Mumbai"],
    "Sales":[5000,7000]
})
jan

feb=pd.DataFrame({
    "Customer":["Chris","Deepak"],
    "City":["Delhi","Kolkata"],
    "Sales":[6500,7200]
})
feb
print()

In [4]:
pd.concat([jan,feb],axis=0).reset_index(drop=True)

  Customer       City  Sales
0     Asha  Bangalore   5000
1  Sanjana     Mumbai   7000
2    Chris      Delhi   6500
3   Deepak    Kolkata   7200

In [5]:
#horizontal stacking
customers=pd.DataFrame({
    "Customers":["Asha","Bala","Chitra"]
})

sales=pd.DataFrame({
    "Sales":[5000,7000,8000]
})

pd.concat([customers,sales],axis=1)

  Customers  Sales
0      Asha   5000
1      Bala   7000
2    Chitra   8000

In [11]:
df1=pd.DataFrame({
    "customer":["Asha","Bala"],
    "Sales":[5000,6000]
})
df2=pd.DataFrame({
    "Customer":["Chitra","Deepa"],
    "Profit":[9000,10000]
})
pd.concat([df1,df2]).reset_index(drop=True).fillna(0)

  customer   Sales Customer   Profit
0     Asha  5000.0        0      0.0
1     Bala  6000.0        0      0.0
2        0     0.0   Chitra   9000.0
3        0     0.0    Deepa  10000.0

#merging (combining tables)
#merge is used when data is stored in seperate tables but linked by keys

Syntax-
pd.merge(left_df,right_df,on="column")

In [18]:
customers=pd.DataFrame({
    "CustomerID":[1,2,3],
    "CustomerName":["Asha","Deepa","Chiranth"],
    "City":["Bangalore","Kolkata","Jaipur"]
})
print(customers)
print()
orders=pd.DataFrame({
    "CustomerID":[1,2,4],
    "OrderValue":[5000,7000,6500]
})
print(orders)

   CustomerID CustomerName       City
0           1         Asha  Bangalore
1           2        Deepa    Kolkata
2           3     Chiranth     Jaipur

   CustomerID  OrderValue
0           1        5000
1           2        7000
2           4        6500

In [ ]:
pd.merge(customers,orders,on="CustomerID")
#this will match rows where customer ID exists in both tables

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore        5000
1           2        Deepa    Kolkata        7000

In [14]:
#when column names don't match
df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})

In [15]:
pd.merge(df1,df2,left_on="custID",right_on="CustomerID")

   custID    Name  CustomerID  Sales
0       1  Anusha           1   5000
1       2  Rajesh           2   7000

In [16]:
#to remove extra key column while merging
#you can rename the column before merge
df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})
df2=df2.rename(columns={"CustomerID":"custID"})
pd.merge(df1,df2,left_on="custID")

MergeError: Must pass "right_on" OR "right_index".

In [ ]:
#outer join - all rows from both tables
pd.merge(customers,orders,on="CustomerID",how="outer")

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore      5000.0
1           2        Deepa    Kolkata      7000.0
2           3     Chiranth     Jaipur         NaN
3           4          NaN        NaN      6500.0

In [21]:
#joining through multiple keys
sales=pd.DataFrame({
    "CustomerID":[1,1,2],
    "Product":["Laptop","Mobile","Tablet"],
    "Sales":[5000,3000,7000]
})

prices=pd.DataFrame({
    "CustomerID":[1,2],
    "Product":["Laptop","Tablet"],
    "Discount":[10,15]
})
pd.merge(sales,prices,on=["CustomerID","Product"])

   CustomerID Product  Sales  Discount
0           1  Laptop   5000        10
1           2  Tablet   7000        15

In [ ]:
#duplicate keys

df1=pd.DataFrame({
    "ID":[1,1],
    "Name":["Asha","Asha"]
})

df2=pd.DataFrame({
    "ID":[1,1],
    "Sales":[5000,6000]
})
pd.merge(df1,df2,on="ID")
#many to many join

   ID  Name  Sales
0   1  Asha   5000
1   1  Asha   6000
2   1  Asha   5000
3   1  Asha   6000

In [28]:
#suffixes
#when both tables contain same column name
df1=pd.DataFrame({
    "ID":[1,2],
    "Sales":[5000,7000]
})

df2=pd.DataFrame({
    "ID":[1,2],
    "Sales":[3000,4000]
})
pd.merge(df1,df2,on="ID",suffixes=("_store1","_store2"))

   ID  Sales_store1  Sales_store2
0   1          5000          3000
1   2          7000          4000