#pandas selection
label based selection using .loc
this is used when selecting by row labels and column names

syntax:
df.loc[row_label,column_label]

#label- based selection
1. .loc
#used when selecting by row labels and column names

In [7]:
import pandas as pd
df=pd.read_csv("North America Restaurants (1).csv")
df.head()

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30

In [8]:
import pandas as pd
df.loc[0,"name"]  #to select single value

'Burger King'

In [ ]:
df.loc[0:2] #multiple rows
#.loc includes end index

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88

In [ ]:
df.loc[:,["name","city"]]   #to identify specific column data

                                name           city
0                        Burger King      Manitowoc
1                       Petro-Canada        Airdrie
2                           Boba Bae    Ashwaubenon
3               1001 Nights Shawarma      Kitchener
4     Chirpyhut Fried Chicken (JlgJ)       Richmond
...                              ...            ...
1495             Grandma's Soul Food       Richmond
1496                  Jimbob's Pizza     Eau Claire
1497                    Petro-Canada      Longueuil
1498                         Denny's        Kingman
1499                      Bean House  Richmond Hill

[1500 rows x 2 columns]

#iloc
poisition based selection
used when selecting by position


syntax:
df.iloc[row_index,column_index]

In [9]:
df.iloc[0,1]  #to select single value using iloc

'Manitowoc'

In [10]:
df.head()

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30

In [ ]:
df.iloc[0:3,0:2]    #to select multiple rows and columns using iloc
#iloc excludes end index

           name         city
0   Burger King    Manitowoc
1  Petro-Canada      Airdrie
2      Boba Bae  Ashwaubenon

In [ ]:
pd.set_option("display.max_rows", None)  #to display everything

In [18]:
pd.reset_option("display.max_rows")  #to reset to default

In [19]:
#boolean masking (filtering)
#filters rows based on condition
df[df["weighted_rating_value"]>2.5] #single condition

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
...,...,...,...,...,...,...,...,...,...,...
1493,Hungarian Kitchen,North Fort Myers,FL,33917,US,"Desserts, Grocery",False,True,3.0,1
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
#for multiple condition 
df[(df["weighted_rating_value"]>2.5) & (df["weighted_rating_value"]<3.5)]  #to filter rows based on multiple conditions

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
21,Little Caesars,Texarkana,TX,75503,US,"American, Comfort Food, Fast Food, Italian, Ki...",True,True,3.3,22
29,Mcdonald's®,Hammond,IN,46323,US,"American, Burgers, Fast Food",False,True,2.8,10
30,Mr. Fish & Chicken,Detroit,MI,48205,US,"American, Comfort Food, Fish And Chips, Wings",True,True,3.1,36
35,Dirty Burger,New York,NY,10011,US,"American, Burger, Burgers, Fast Food, Vegan Fr...",True,True,3.3,19
49,Mak's Pasta & Salad,Nashville,TN,37219,US,"American, Chicken, Comfort Food, Dessert, Dess...",True,True,2.7,177
...,...,...,...,...,...,...,...,...,...,...
1479,McDonald's,Cincinnati,OH,45251,US,"American, Bakery, Breakfast, Burger, Burgers, ...",False,True,2.9,79
1480,Deviled Soul Food,Philadelphia,PA,19123,US,"Alcohol, Comfort Food, Soul Food, Southern",True,True,2.7,87
1484,McDonald's,Richmond,RI,2898,US,"American, Burger, Fast Food",False,True,3.2,26
1493,Hungarian Kitchen,North Fort Myers,FL,33917,US,"Desserts, Grocery",False,True,3.0,1
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22

In [25]:
#or condition
df[(df["weighted_rating_value"]>4.5) | (df["pickup_enabled"]==False)]

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
6,Petro-Canada,Edmonton,AB,T6X,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.8,1
9,Etoile Mirabel,Mirabel,QC,J7J,CA,"American, Beau, Bon, Local, Burgers, Dessert, ...",True,True,4.6,35
10,Petro-Canada,Burlington,ON,L7L,CA,"Baby, Ben & Jerry's, Convenience, Cool Treats,...",True,True,4.7,1
...,...,...,...,...,...,...,...,...,...,...
1491,Smokey's BBQ Sandwiches,Orlando,FL,32832,US,"Barbeque, Bbq, Pickup, Sandwiches, Takeout",False,True,2.5,4
1492,Golden Chick,Dallas,TX,75217,US,"Bbq, Family Friendly, Family Meals, Fast Food,...",False,True,3.7,116
1493,Hungarian Kitchen,North Fort Myers,FL,33917,US,"Desserts, Grocery",False,True,3.0,1
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [6]:
import pandas as pd

In [9]:
df[~(df['country'] == 'CA')]    #to filter rows where country is not CA

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
7,El Valle Verde,Cincinnati,OH,45205,US,"Burritos, Dessert, Kids Menu, Latin American, ...",True,True,2.4,5
8,Rock Salad,Dubuque,IA,52001,US,"American, Bowls, Dessert, Healthy Food, Salads...",True,True,4.3,35
11,J. Alexander's : Jacksonville,Jacksonville,FL,32246,US,"American (New), Comfort Food, Desserts, Steakh...",True,True,4.1,34
...,...,...,...,...,...,...,...,...,...,...
1493,Hungarian Kitchen,North Fort Myers,FL,33917,US,"Desserts, Grocery",False,True,3.0,1
1494,The Saffron Biryani,Jersey City,NJ,7306,US,"Chicken, Coffee And Tea, Dessert, Indian, Seaf...",True,True,2.5,63
1495,Grandma's Soul Food,Richmond,VA,23234,US,"American, Burgers, Chicken, Dessert, Dinner, K...",True,True,2.0,5
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22

In [10]:
#query method
#similar to sql method
df.query('weighted_rating_value>3.6')   #to filter rows based on multiple conditions using query method

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
...,...,...,...,...,...,...,...,...,...,...
1490,33 Acres Brewing,Vancouver,BC,V5Y,CA,"Alcohol, Beer, Bière, Boissons Alcoolisées, Ca...",True,True,4.3,1
1492,Golden Chick,Dallas,TX,75217,US,"Bbq, Family Friendly, Family Meals, Fast Food,...",False,True,3.7,116
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
df.iloc[1:2]    #to select specific row using iloc

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1